### ISSUE TITLE
Issue with upscaling/denoising.

### ISSUE THREAD

**Issue by xiyomuque** [kanjieater/ComicEater#4]
When your program is upscaling the folder with png pictures in it, it creates upscaled pictures in the same folder, which it can't do because the result would be the same name and extention. This would work with jpg folders, but with png manga it doesn't work.
waifu2x allows to create upscaled pictures in another folder which would solve this issue if inbuild into the upscaling properly.
"sync () => callProgram('waifu2x-ncnn-vulkan.exe', ['-i', wrappedInput, '-o', wrappedInput, '-n', '2', '-s', '2'])" this is part of code which puts upscaled pictures in the same folder as originals (impossible with pngs). So the whole thing results in this error log. "Error: Before and after image count did not match after upscaling"

**Comment by xiyomuque** [comment]
alternatively one could make any .png image files initially located in the folder be renamed to .jpg or whatever. and then begin the process of upscaling.

**Comment by kanjieater** [comment]
Thanks for letting me know. 

At this point I might investigate this at some point but its not a high priority given upscaling the files permanently is a bit clunky, given better algorithms will come out and you should always keep the original version alongside the upscaled version. 

I have stopped using the upscaling feature as of the release of https://github.com/Snd-R/kurp. This allows for on the fly upscaling from komga. In the meantime I'd recommend trying that if your gpu can handle it.

**Comment by xiyomuque** [comment]
what better algorithms will come out?

**Comment by xiyomuque** [comment]
waifu2x ncnn is pretty darn good, considering I had troubles reading the blurry mess that I had and now I actually enjoy reading it.

**Comment by kanjieater** [comment]
Data science will continue to make advances here. I was in the same situation before, when I wrote this and its already changed. Realcugan, one of the models included in Kurp makes waifu2x scans look like standard def while realcugan looks like HD. It's that big of a difference.

**Comment by xiyomuque** [comment]
ah, I see, thanks, I'll try it out for sure!

**Comment by xiyomuque** [comment]
my other issue wasn't related to this one. this one can easily be solved by adding -f webp to the end of waifu2x command, overlapping png is an issue, while overlapping webp is hardly one. also I tried out realcugan, it's way worse for manga than waifu2x tbh, it thoroughly kills the details of halftones, while waifu2x makes them more definite and sharp.

**Comment by xiyomuque** [comment]
I guess it's more of a personal preference, but definitely not better.
