### ISSUE TITLE
folder structure bug

### ISSUE THREAD

**Issue by yomq** [kanjieater/ComicEater#5]
again, I really want to use this program, but upscaling doesn't work for folders/archives which contain pictures directly inside them, I tried to fix it today, but I couldn't understand the principle by which upscaling looks for target folder, there was imageDir const, extractedArchiveDir, imagePath, also I don't know js ¯\_(ツ)_/¯. however trimming images which are contained within one source folder works. idk why...

**Comment by kanjieater** [comment]
I think this is all still related to your original issue, lets keep it contained to that issue for the image names overlapping for pngs. I don't have any update beyond whats there.
